version: "3.9"
services:
  es01:
    container_name: "es01"
    image: "docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_STACK_VERSION}"
    ports:
      - "${ELASTICSEARCH_PORT}:9200"    # [docker host port]:[in container port]
    environment:
      - node.name=elasticsearch-01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=$CERTS_DIR/es01/es01.key
      - xpack.security.http.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.http.ssl.certificate=$CERTS_DIR/es01/es01.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.transport.ssl.certificate=$CERTS_DIR/es01/es01.crt
      - xpack.security.transport.ssl.key=$CERTS_DIR/es01/es01.key
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - certs:$CERTS_DIR
      - esData:/usr/share/elasticsearch/data
      - esConfig:/usr/share/elasticsearch/config
    networks:
      - elastic
    healthcheck:
      test: curl --cacert $CERTS_DIR/ca/ca.crt -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 15s
      timeout: 5s
      retries: 10

  kibana:
    container_name: "Kibana"
    image: "docker.elastic.co/kibana/kibana:${ELASTIC_STACK_VERSION}"
    depends_on: { "es01": { "condition": "service_healthy" } }
    ports:
      - "${KIBANA_PORT}:5601"           # [docker host port]:[in container port]
    environment:
      SERVERNAME: localhost
      ELASTICSEARCH_URL: https://es01:9200
      ELASTICSEARCH_HOSTS: https://es01:9200
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: $KIBANA_SYSTEM_PASS
      ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES: $CERTS_DIR/ca/ca.crt
      SERVER_SSL_ENABLED: "true"
      SERVER_SSL_KEY: $CERTS_DIR/kibana/kibana.key
      SERVER_SSL_CERTIFICATE: $CERTS_DIR/kibana/kibana.crt
    volumes:
      - certs:$CERTS_DIR
      - kibanaConfig:/usr/share/kibana/config
    networks:
      - elastic
    healthcheck:
      test: curl --cacert $CERTS_DIR/ca/ca.crt -s https://localhost:5601 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 15s
      timeout: 5s
      retries: 10

  indexer-server:
    container_name: "Spring-indexer"
    environment:

      elastic_host: es01                # the elastic host ip

      elastic_port: '9200'              # the elastic host port

      kibana_host: kibana               # the kibana host ip

      kibana_port: '5601'               # the kibana host port

      ssl_connection: 'true'            # to use SSL (HTTPS) or not

      elastic_user: $INDEXER_USERNAME   # the elastic username for indexer

      elastic_pass: $INDEXER_PASSWORD   # the elastic password for indexer

      indexer_multithreading: 'true'    # if you want multithreading; each river will have a single thread

      threads: $INDEXER_MAX_THREADS     # in case of multithreading, the max number of concurrent working threads

      log_level: "info"                 # the log level (info or debug)

      cache_duration_in_seconds: 10     # number of second to cache dashboard data

    tty: true

    ports:
      - "${INDEXER_PORT}:8080"          # [docker host port]:[in container port]
    volumes:
      - indexerDB:/DB
      - certs:/certs
    networks:
      - elastic
    build: .
    image: indexer-server

  nginx:
    container_name: "Nginx"
    image: "nginx:${NGINX_VERSION}"
    depends_on: { "kibana": { "condition": "service_healthy" } }
    ports:
      - "${PUBLIC_KIBANA_PORT}:6601"    # [docker host port]:[in container port]
    volumes:
      - nginxConfig:/etc/nginx/conf.d/
      - nginxLog:/var/log/nginx
      - certs:/certs
    networks:
      - elastic

volumes:
  esData:
    driver: local
  esConfig:
    driver: local
  kibanaConfig:
    driver: local
  certs:
    driver: local
  indexerDB:
    driver: local
  nginxConfig:
    driver: local
  nginxLog:
    driver: local

networks:
  elastic:
    driver: bridge